[package]
name = "erp-backend"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
sqlx = { version = "0.7", features = ["postgres", "runtime-tokio-native-tls"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
chrono = "0.4"
# rust-decimal = "1.26"
jsonwebtoken = "9.3.1"
dotenv = "0.15"
log = "0.4"
tracing = "0.1"
# lazystatic = "1.4"
